#!/bin/bash
# scripts/workflow/copilot-comments.sh
# Fetches and formats UNRESOLVED Copilot review comments for a PR.
# Output is ready to paste into agent prompts.
#
# Uses GraphQL to distinguish resolved vs unresolved threads, so only
# actionable comments are shown. Resolved threads are hidden.
#
# Usage:
#   ./scripts/workflow/copilot-comments.sh 918          # Show unresolved Copilot comments
#   ./scripts/workflow/copilot-comments.sh 918 --raw    # JSON output
#   ./scripts/workflow/copilot-comments.sh 918 --all    # Include resolved threads too

set -euo pipefail

OWNER="timothyfroehlich"
REPO="PinPoint"

if [ $# -lt 1 ]; then
    echo "Usage: $0 <PR_NUMBER> [--raw|--all]"
    exit 1
fi

PR=$1
if ! [[ "$PR" =~ ^[0-9]+$ ]]; then
    echo "Error: PR number must be numeric (e.g. '945'); received '$PR'."
    exit 1
fi
MODE="${2:-}"

case "$MODE" in
    ""|"--raw"|"--all") ;;
    *) echo "Error: unknown mode '$MODE'."; echo "Usage: $0 <PR_NUMBER> [--raw|--all]"; exit 1 ;;
esac

INCLUDE_RESOLVED=false
if [ "$MODE" = "--all" ]; then
    INCLUDE_RESOLVED=true
fi

# Fetch all review threads via GraphQL
threads_json=$(gh api graphql -f query="
{
  repository(owner: \"$OWNER\", name: \"$REPO\") {
    pullRequest(number: $PR) {
      reviewThreads(first: 100) {
        nodes {
          isResolved
          comments(first: 1) {
            nodes {
              author { login }
              body
              path
              line
            }
          }
        }
      }
    }
  }
}")

# Extract Copilot comments
comments=$(echo "$threads_json" | jq --argjson includeResolved "$INCLUDE_RESOLVED" '
  [.data.repository.pullRequest.reviewThreads.nodes[]
   | select($includeResolved or (.isResolved == false))
   | select(.comments.nodes | length > 0)
   | .comments.nodes[0] as $comment
   | select(
       $comment.author.login == "copilot-pull-request-reviewer"
       or $comment.author.login == "copilot-pull-request-reviewer[bot]"
     )
   | {
       path: $comment.path,
       line: $comment.line,
       body: $comment.body,
       resolved: .isResolved
     }]')

count=$(echo "$comments" | jq 'length')

if [ "$count" -eq 0 ]; then
    if [ "$MODE" = "--all" ]; then
        echo "No Copilot comments on PR #${PR}."
    else
        echo "No unresolved Copilot comments on PR #${PR}."
    fi
    exit 0
fi

if [ "$MODE" = "--raw" ]; then
    echo "$comments" | jq -c '.[]'
    exit 0
fi

label="unresolved "
if [ "$MODE" = "--all" ]; then
    label=""
fi

echo "## Copilot Comments on PR #${PR} (${count} ${label}comments)"
echo ""
echo "> NOTE: These comments were generated by GitHub Copilot, which may lack full"
echo "> context of the problem being solved. Evaluate critically — not all suggestions"
echo "> warrant changes. Reply with justification when ignoring a comment."
echo ""

echo "$comments" | jq -r '.[] | "### \(.path):\(.line // "N/A")\n\(.body)\n\n---\n"'
