coverage:
  status:
    # Don't enforce overall project coverage (allows gradual improvement)
    project: off

    # Enforce 60% coverage on new/changed lines only (delta coverage)
    patch:
      default:
        target: 60%
        threshold: 0% # No tolerance - exactly 60% required

# No PR comments, just status checks
comment: false

# Exclude paths that match vitest coverage excludes
ignore:
  - "src/app/**" # Server Components (tested via E2E)
  - "src/components/ui/**" # shadcn/ui library components
  - "**/*.d.ts"
  - "**/types.ts"
  - "**/*.config.*"
  - "src/test/**"
