CREATE INDEX "Attachment_organizationId_idx" ON "Attachment" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Attachment_issueId_idx" ON "Attachment" USING btree ("issueId");--> statement-breakpoint
CREATE INDEX "Comment_issueId_idx" ON "Comment" USING btree ("issueId");--> statement-breakpoint
CREATE INDEX "Comment_authorId_idx" ON "Comment" USING btree ("authorId");--> statement-breakpoint
CREATE INDEX "IssueHistory_organizationId_idx" ON "IssueHistory" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "IssueHistory_issueId_idx" ON "IssueHistory" USING btree ("issueId");--> statement-breakpoint
CREATE INDEX "IssueHistory_type_idx" ON "IssueHistory" USING btree ("type");--> statement-breakpoint
CREATE INDEX "IssueStatus_organizationId_idx" ON "IssueStatus" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Issue_organizationId_idx" ON "Issue" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Issue_machineId_idx" ON "Issue" USING btree ("machineId");--> statement-breakpoint
CREATE INDEX "Issue_statusId_idx" ON "Issue" USING btree ("statusId");--> statement-breakpoint
CREATE INDEX "Issue_priorityId_idx" ON "Issue" USING btree ("priorityId");--> statement-breakpoint
CREATE INDEX "Issue_assignedToId_idx" ON "Issue" USING btree ("assignedToId");--> statement-breakpoint
CREATE INDEX "Issue_createdById_idx" ON "Issue" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "Priority_organizationId_idx" ON "Priority" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Upvote_issueId_idx" ON "Upvote" USING btree ("issueId");--> statement-breakpoint
CREATE INDEX "Upvote_userId_issueId_idx" ON "Upvote" USING btree ("userId","issueId");--> statement-breakpoint
CREATE INDEX "Location_organizationId_idx" ON "Location" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Machine_qrCodeId_idx" ON "Machine" USING btree ("qrCodeId");--> statement-breakpoint
CREATE INDEX "Machine_organizationId_idx" ON "Machine" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Machine_locationId_idx" ON "Machine" USING btree ("locationId");--> statement-breakpoint
CREATE INDEX "Machine_modelId_idx" ON "Machine" USING btree ("modelId");--> statement-breakpoint
CREATE INDEX "Machine_ownerId_idx" ON "Machine" USING btree ("ownerId");--> statement-breakpoint
CREATE INDEX "Membership_userId_organizationId_idx" ON "Membership" USING btree ("userId","organizationId");--> statement-breakpoint
CREATE INDEX "Membership_organizationId_idx" ON "Membership" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Organization_subdomain_idx" ON "Organization" USING btree ("subdomain");--> statement-breakpoint
CREATE INDEX "_RolePermissions_roleId_idx" ON "_RolePermissions" USING btree ("A");--> statement-breakpoint
CREATE INDEX "_RolePermissions_permissionId_idx" ON "_RolePermissions" USING btree ("B");--> statement-breakpoint
CREATE INDEX "Role_organizationId_idx" ON "Role" USING btree ("organizationId");