/**
 * Paths to pre-saved browser auth state files.
 *
 * Generated by the `auth-setup` Playwright project (e2e/auth.setup.ts).
 * Tests opt in via: test.use({ storageState: STORAGE_STATE.<role> })
 *
 * The e2e/.auth/ directory is gitignored.
 */
export const STORAGE_STATE = {
  admin: "e2e/.auth/admin.json",
  member: "e2e/.auth/member.json",
  technician: "e2e/.auth/technician.json",
} as const;
