/**
 * Worker-Scoped PGlite Setup
 *
 * CRITICAL: Per CORE-TEST-001, we use ONE worker-scoped PGlite instance
 * for all tests in a worker. Per-test instances cause system lockups.
 *
 * Schema is generated from src/server/db/schema.ts using drizzle-kit.
 * Run `npm run test:generate-schema` to regenerate when schema changes.
 */

import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import { beforeAll, afterEach } from "vitest";
import * as schema from "~/server/db/schema";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Worker-scoped instance - created once per worker
let pgliteInstance: PGlite | undefined;
let testDb: ReturnType<typeof drizzle> | undefined;

/**
 * Get the worker-scoped test database instance.
 * Creates and initializes on first call, returns cached instance thereafter.
 */
export async function getTestDb() {
  if (testDb) {
    return testDb;
  }

  // Create PGlite instance
  pgliteInstance = new PGlite();

  // Create Drizzle instance
  testDb = drizzle(pgliteInstance, { schema });

  // Load schema SQL generated by drizzle-kit
  // This ensures test schema matches production schema exactly
  const schemaPath = join(
    __dirname,
    "migrations",
    "0000_strange_sister_grimm.sql"
  );
  const schemaSql = readFileSync(schemaPath, "utf-8");

  // Apply schema (create tables and constraints)
  await pgliteInstance.exec(schemaSql);

  return testDb;
}

/**
 * Clean up helper - deletes all rows from all tables.
 * Use in afterEach to ensure test isolation.
 */
export async function cleanupTestDb() {
  if (!testDb) return;

  // Delete in order to respect foreign key constraints
  await testDb.delete(schema.issueComments);
  await testDb.delete(schema.issues);
  await testDb.delete(schema.machines);
  await testDb.delete(schema.userProfiles);
}

/**
 * Setup function for integration tests.
 * Call this in describe blocks that need database access.
 */
export function setupTestDb() {
  beforeAll(async () => {
    await getTestDb();
  });

  afterEach(async () => {
    await cleanupTestDb();
  });
}
