// Temporary type definitions for service layer
// These will be replaced by generated Prisma types once client generation is working

// Mock Prisma Client types
export interface ExtendedPrismaClient {
  collection: {
    findMany: (args?: any) => Promise<any>;
    findUnique: (args: any) => Promise<any>;
    findFirst: (args: any) => Promise<any>;
    create: (args: any) => Promise<any>;
    update: (args: any) => Promise<any>;
    deleteMany: (args: any) => Promise<{ count: number }>;
  };
  collectionType: {
    findMany: (args?: any) => Promise<any>;
    findUnique: (args: any) => Promise<any>;
    update: (args: any) => Promise<any>;
  };
  machine: {
    findMany: (args?: any) => Promise<any>;
    findUnique: (args: any) => Promise<any>;
    create: (args: any) => Promise<any>;
    update: (args: any) => Promise<any>;
    delete: (args: any) => Promise<any>;
    count: (args?: any) => Promise<number>;
  };
  notification: {
    create: (args: any) => Promise<any>;
    findMany: (args?: any) => Promise<any>;
    updateMany: (args: any) => Promise<any>;
    count: (args?: any) => Promise<number>;
  };
  comment: {
    findMany: (args?: any) => Promise<any>;
    deleteMany: (args: any) => Promise<{ count: number }>;
    count: (args?: any) => Promise<number>;
    update: (args: any) => Promise<any>;
  };
  issueHistory: {
    create: (args: any) => Promise<any>;
    findMany: (args?: any) => Promise<any>;
  };
  issue: {
    findUnique: (args: any) => Promise<any>;
    count: (args?: any) => Promise<number>;
  };
  pinballMapConfig: {
    findUnique: (args: any) => Promise<any>;
    upsert: (args: any) => Promise<any>;
  };
  location: {
    findUnique: (args: any) => Promise<any>;
    findMany: (args?: any) => Promise<any>;
    update: (args: any) => Promise<any>;
  };
  model: {
    findUnique: (args: any) => Promise<any>;
    create: (args: any) => Promise<any>;
  };
  $accelerate: {
    invalidate: () => any;
    ttl: () => any;
  };
}

export interface Collection {
  id: string;
  name: string;
  typeId: string;
  locationId: string | null;
  description: string | null;
  isManual: boolean;
  isSmart: boolean;
  organizationId: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface CollectionType {
  id: string;
  name: string;
  displayName: string | null;
  organizationId: string;
  isAutoGenerated: boolean;
  isEnabled: boolean;
  sourceField: string | null;
  sortOrder: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface User {
  id: string;
  name: string | null;
  email: string;
  profilePicture: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface IssueStatus {
  id: string;
  name: string;
  organizationId: string;
  isResolved: boolean;
  sortOrder: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface Notification {
  id: string;
  userId: string;
  type: NotificationType;
  message: string;
  entityType: NotificationEntity | null;
  entityId: string | null;
  actionUrl: string | null;
  read: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Comment {
  id: string;
  content: string;
  issueId: string;
  authorId: string;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
  deletedBy: string | null;
}

export interface Machine {
  id: string;
  name: string;
  organizationId: string;
  locationId: string;
  modelId: string;
  ownerId: string | null;
  qrCodeId: string;
  qrCodeUrl: string | null;
  qrCodeGeneratedAt: Date | null;
  ownerNotificationsEnabled: boolean;
  notifyOnNewIssues: boolean;
  notifyOnStatusChanges: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export enum NotificationType {
  ISSUE_CREATED = "ISSUE_CREATED",
  ISSUE_UPDATED = "ISSUE_UPDATED", 
  ISSUE_ASSIGNED = "ISSUE_ASSIGNED",
  COMMENT_ADDED = "COMMENT_ADDED",
  STATUS_CHANGED = "STATUS_CHANGED"
}

export enum NotificationEntity {
  ISSUE = "ISSUE",
  COMMENT = "COMMENT",
  MACHINE = "MACHINE"
}

export enum ActivityType {
  CREATED = "CREATED",
  STATUS_CHANGED = "STATUS_CHANGED",
  ASSIGNED = "ASSIGNED",
  COMMENT_DELETED = "COMMENT_DELETED",
  SYSTEM = "SYSTEM"
}

// Prisma utility types
export namespace Prisma {
  export type CollectionGetPayload<T> = Collection & {
    type: CollectionType;
    _count: { machines: number };
    isManual: boolean;
  };
  
  export interface MachineGetPayload<T> {
    model: { manufacturer: string | null };
  }
  
  export type CollectionTypeGetPayload<T> = CollectionType & {
    _count: { collections: number };
  };
}