#!/usr/bin/env tsx
/**
 * Ensures test schema is up-to-date with src/server/db/schema.ts
 * Regenerates only if schema.ts is newer than schema.sql
 *
 * Concurrency safety:
 * - Writes to a temp file then renames atomically so readers never see
 *   a partial schema.sql (fixes preflight parallel-race PP-3vdr.5).
 * - Uses a lockfile (wx open flag) so only one process regenerates at a
 *   time; the second process skips regeneration since the first will
 *   have finished by the time the lock file is gone.
 */
import {
  statSync,
  existsSync,
  openSync,
  closeSync,
  writeFileSync,
  renameSync,
  unlinkSync,
} from "node:fs";
import { execSync } from "node:child_process";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";
import { randomBytes } from "node:crypto";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ROOT = resolve(__dirname, "..");
const SCHEMA_TS = resolve(ROOT, "src/server/db/schema.ts");
const SCHEMA_SQL = resolve(ROOT, "src/test/setup/schema.sql");
const LOCK_FILE = resolve(ROOT, "src/test/setup/.schema.lock");

function getModifiedTime(path: string): number {
  try {
    return statSync(path).mtimeMs;
  } catch (error: unknown) {
    if (
      error &&
      typeof error === "object" &&
      "code" in error &&
      error.code === "ENOENT"
    ) {
      return 0;
    }
    throw error;
  }
}

/**
 * Try to acquire an exclusive lockfile using the O_EXCL (wx) flag.
 * Returns the file descriptor if acquired, or null if already locked.
 */
function tryAcquireLock(): number | null {
  try {
    const fd = openSync(LOCK_FILE, "wx");
    return fd;
  } catch (error: unknown) {
    if (
      error &&
      typeof error === "object" &&
      "code" in error &&
      error.code === "EEXIST"
    ) {
      return null;
    }
    throw error;
  }
}

function releaseLock(fd: number): void {
  try {
    closeSync(fd);
  } catch {
    // ignore close errors
  }
  try {
    unlinkSync(LOCK_FILE);
  } catch {
    // ignore unlink errors (already cleaned up)
  }
}

/**
 * Regenerate schema.sql atomically:
 * 1. Run drizzle-kit export and capture stdout.
 * 2. Write output to a uniquely-named temp file.
 * 3. Rename the temp file over schema.sql (atomic on POSIX).
 */
function regenerateSchemaAtomic(): void {
  const suffix = randomBytes(6).toString("hex");
  const tmpFile = resolve(tmpdir(), `schema-${suffix}.sql`);

  try {
    const sql = execSync(
      "pnpm exec drizzle-kit export --dialect=postgresql --schema=./src/server/db/schema.ts",
      { cwd: ROOT }
    );
    writeFileSync(tmpFile, sql);
    renameSync(tmpFile, SCHEMA_SQL);
  } catch (error) {
    // Clean up temp file on failure
    try {
      unlinkSync(tmpFile);
    } catch {
      // ignore
    }
    throw error;
  }
}

function main() {
  const schemaExists = existsSync(SCHEMA_SQL);
  const schemaTsTime = getModifiedTime(SCHEMA_TS);
  const schemaSqlTime = getModifiedTime(SCHEMA_SQL);

  const needsRegeneration = !schemaExists || schemaTsTime > schemaSqlTime;

  if (!needsRegeneration) {
    console.log("✓ Test schema up-to-date");
    return;
  }

  // Try to acquire the exclusive lock.
  const lockFd = tryAcquireLock();

  if (lockFd === null) {
    // Another process is regenerating — skip; the other process will
    // finish before tests start (they each call this script first).
    console.log("✓ Test schema regeneration in progress elsewhere — skipping");
    return;
  }

  try {
    // Re-check inside the lock — another process may have just finished.
    const schemaExistsNow = existsSync(SCHEMA_SQL);
    const schemaSqlTimeNow = getModifiedTime(SCHEMA_SQL);
    if (schemaExistsNow && schemaTsTime <= schemaSqlTimeNow) {
      console.log("✓ Test schema up-to-date (regenerated by another process)");
      return;
    }

    if (!schemaExistsNow) {
      console.log("⚠️  Test schema missing, generating...");
    } else {
      console.log("⚠️  Test schema stale, regenerating...");
    }

    regenerateSchemaAtomic();
    console.log("✅ Test schema updated");
  } catch (error) {
    console.error("❌ Failed to ensure test schema:");
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  } finally {
    releaseLock(lockFd);
  }
}

main();
