CREATE TYPE "public"."NotificationFrequency" AS ENUM('IMMEDIATE', 'DAILY', 'WEEKLY', 'NEVER');--> statement-breakpoint
CREATE TYPE "public"."NotificationEntity" AS ENUM('ISSUE', 'MACHINE', 'COMMENT', 'ORGANIZATION');--> statement-breakpoint
CREATE TYPE "public"."NotificationType" AS ENUM('ISSUE_CREATED', 'ISSUE_UPDATED', 'ISSUE_ASSIGNED', 'ISSUE_COMMENTED', 'MACHINE_ASSIGNED', 'SYSTEM_ANNOUNCEMENT');--> statement-breakpoint
CREATE TYPE "public"."ActivityType" AS ENUM('CREATED', 'STATUS_CHANGED', 'ASSIGNED', 'PRIORITY_CHANGED', 'COMMENTED', 'COMMENT_DELETED', 'ATTACHMENT_ADDED', 'MERGED', 'RESOLVED', 'REOPENED', 'SYSTEM');--> statement-breakpoint
CREATE TYPE "public"."StatusCategory" AS ENUM('NEW', 'IN_PROGRESS', 'RESOLVED');--> statement-breakpoint
CREATE TABLE "Account" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"type" text NOT NULL,
	"provider" text NOT NULL,
	"providerAccountId" text NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" timestamp,
	"token_type" text,
	"scope" text,
	"id_token" text,
	"session_state" text
);
--> statement-breakpoint
CREATE TABLE "Session" (
	"id" text PRIMARY KEY NOT NULL,
	"sessionToken" text NOT NULL,
	"userId" text NOT NULL,
	"expires" timestamp NOT NULL,
	CONSTRAINT "Session_sessionToken_unique" UNIQUE("sessionToken")
);
--> statement-breakpoint
CREATE TABLE "User" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text,
	"email" text,
	"emailVerified" timestamp,
	"image" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"bio" text,
	"profilePicture" text,
	"emailNotificationsEnabled" boolean DEFAULT true NOT NULL,
	"pushNotificationsEnabled" boolean DEFAULT false NOT NULL,
	"notificationFrequency" "NotificationFrequency" DEFAULT 'IMMEDIATE' NOT NULL,
	CONSTRAINT "User_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "VerificationToken" (
	"identifier" text NOT NULL,
	"token" text NOT NULL,
	"expires" timestamp NOT NULL,
	CONSTRAINT "VerificationToken_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "CollectionType" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"organizationId" text NOT NULL,
	"isAutoGenerated" boolean DEFAULT false NOT NULL,
	"isEnabled" boolean DEFAULT true NOT NULL,
	"sourceField" text,
	"generationRules" json,
	"displayName" text,
	"description" text,
	"sortOrder" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Collection" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"typeId" text NOT NULL,
	"locationId" text,
	"isSmart" boolean DEFAULT false NOT NULL,
	"isManual" boolean DEFAULT true NOT NULL,
	"description" text,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"filterCriteria" json
);
--> statement-breakpoint
CREATE TABLE "Notification" (
	"id" text PRIMARY KEY NOT NULL,
	"message" text NOT NULL,
	"read" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"userId" text NOT NULL,
	"type" "NotificationType" NOT NULL,
	"entityType" "NotificationEntity",
	"entityId" text,
	"actionUrl" text
);
--> statement-breakpoint
CREATE TABLE "PinballMapConfig" (
	"id" text PRIMARY KEY NOT NULL,
	"organizationId" text NOT NULL,
	"apiEnabled" boolean DEFAULT false NOT NULL,
	"apiKey" text,
	"autoSyncEnabled" boolean DEFAULT false NOT NULL,
	"syncIntervalHours" integer DEFAULT 24 NOT NULL,
	"lastGlobalSync" timestamp,
	"createMissingModels" boolean DEFAULT true NOT NULL,
	"updateExistingData" boolean DEFAULT false NOT NULL,
	CONSTRAINT "PinballMapConfig_organizationId_unique" UNIQUE("organizationId")
);
--> statement-breakpoint
CREATE TABLE "Attachment" (
	"id" text PRIMARY KEY NOT NULL,
	"url" text NOT NULL,
	"fileName" text NOT NULL,
	"fileType" text NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"organizationId" text NOT NULL,
	"issueId" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Comment" (
	"id" text PRIMARY KEY NOT NULL,
	"content" text NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" text,
	"issueId" text NOT NULL,
	"authorId" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "IssueHistory" (
	"id" text PRIMARY KEY NOT NULL,
	"field" text NOT NULL,
	"oldValue" text,
	"newValue" text,
	"changedAt" timestamp DEFAULT now() NOT NULL,
	"organizationId" text NOT NULL,
	"actorId" text,
	"type" "ActivityType" NOT NULL,
	"issueId" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "IssueStatus" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"category" "StatusCategory" NOT NULL,
	"organizationId" text NOT NULL,
	"isDefault" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Issue" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"consistency" text,
	"checklist" json,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"resolvedAt" timestamp,
	"reporterEmail" text,
	"submitterName" text,
	"organizationId" text NOT NULL,
	"machineId" text NOT NULL,
	"statusId" text NOT NULL,
	"priorityId" text NOT NULL,
	"createdById" text,
	"assignedToId" text
);
--> statement-breakpoint
CREATE TABLE "Priority" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"order" integer NOT NULL,
	"organizationId" text NOT NULL,
	"isDefault" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Upvote" (
	"id" text PRIMARY KEY NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"issueId" text NOT NULL,
	"userId" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Location" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"organizationId" text NOT NULL,
	"street" text,
	"city" text,
	"state" text,
	"zip" text,
	"phone" text,
	"website" text,
	"latitude" real,
	"longitude" real,
	"description" text,
	"pinballMapId" integer,
	"regionId" text,
	"lastSyncAt" timestamp,
	"syncEnabled" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Machine" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"organizationId" text NOT NULL,
	"locationId" text NOT NULL,
	"modelId" text NOT NULL,
	"ownerId" text,
	"ownerNotificationsEnabled" boolean DEFAULT true NOT NULL,
	"notifyOnNewIssues" boolean DEFAULT true NOT NULL,
	"notifyOnStatusChanges" boolean DEFAULT true NOT NULL,
	"notifyOnComments" boolean DEFAULT false NOT NULL,
	"qrCodeId" text NOT NULL,
	"qrCodeUrl" text,
	"qrCodeGeneratedAt" timestamp,
	CONSTRAINT "Machine_qrCodeId_unique" UNIQUE("qrCodeId")
);
--> statement-breakpoint
CREATE TABLE "Model" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"manufacturer" text,
	"year" integer,
	"ipdbId" text,
	"opdbId" text,
	"machineType" text,
	"machineDisplay" text,
	"isActive" boolean DEFAULT true NOT NULL,
	"ipdbLink" text,
	"opdbImgUrl" text,
	"kineticistUrl" text,
	"isCustom" boolean DEFAULT false NOT NULL,
	CONSTRAINT "Model_ipdbId_unique" UNIQUE("ipdbId"),
	CONSTRAINT "Model_opdbId_unique" UNIQUE("opdbId")
);
--> statement-breakpoint
CREATE TABLE "Membership" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"organizationId" text NOT NULL,
	"roleId" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Organization" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"subdomain" text NOT NULL,
	"logoUrl" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "Organization_subdomain_unique" UNIQUE("subdomain")
);
--> statement-breakpoint
CREATE TABLE "Permission" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text,
	CONSTRAINT "Permission_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "_RolePermissions" (
	"A" text NOT NULL,
	"B" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Role" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"organizationId" text NOT NULL,
	"isDefault" boolean DEFAULT false NOT NULL,
	"isSystem" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "_RolePermissions" ADD CONSTRAINT "_RolePermissions_A_Role_id_fk" FOREIGN KEY ("A") REFERENCES "public"."Role"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "_RolePermissions" ADD CONSTRAINT "_RolePermissions_B_Permission_id_fk" FOREIGN KEY ("B") REFERENCES "public"."Permission"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "CollectionType_organizationId_idx" ON "CollectionType" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "CollectionType_isEnabled_idx" ON "CollectionType" USING btree ("isEnabled");--> statement-breakpoint
CREATE INDEX "CollectionType_sortOrder_idx" ON "CollectionType" USING btree ("sortOrder");--> statement-breakpoint
CREATE INDEX "Collection_typeId_idx" ON "Collection" USING btree ("typeId");--> statement-breakpoint
CREATE INDEX "Notification_userId_read_idx" ON "Notification" USING btree ("userId","read");--> statement-breakpoint
CREATE INDEX "Notification_userId_createdAt_idx" ON "Notification" USING btree ("userId","createdAt");--> statement-breakpoint
CREATE INDEX "PinballMapConfig_organizationId_idx" ON "PinballMapConfig" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Attachment_organizationId_idx" ON "Attachment" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Attachment_issueId_idx" ON "Attachment" USING btree ("issueId");--> statement-breakpoint
CREATE INDEX "Comment_issueId_idx" ON "Comment" USING btree ("issueId");--> statement-breakpoint
CREATE INDEX "Comment_authorId_idx" ON "Comment" USING btree ("authorId");--> statement-breakpoint
CREATE INDEX "IssueHistory_organizationId_idx" ON "IssueHistory" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "IssueHistory_issueId_idx" ON "IssueHistory" USING btree ("issueId");--> statement-breakpoint
CREATE INDEX "IssueHistory_type_idx" ON "IssueHistory" USING btree ("type");--> statement-breakpoint
CREATE INDEX "IssueStatus_organizationId_idx" ON "IssueStatus" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Issue_organizationId_idx" ON "Issue" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Issue_machineId_idx" ON "Issue" USING btree ("machineId");--> statement-breakpoint
CREATE INDEX "Issue_statusId_idx" ON "Issue" USING btree ("statusId");--> statement-breakpoint
CREATE INDEX "Issue_priorityId_idx" ON "Issue" USING btree ("priorityId");--> statement-breakpoint
CREATE INDEX "Issue_assignedToId_idx" ON "Issue" USING btree ("assignedToId");--> statement-breakpoint
CREATE INDEX "Issue_createdById_idx" ON "Issue" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "Priority_organizationId_idx" ON "Priority" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Upvote_issueId_idx" ON "Upvote" USING btree ("issueId");--> statement-breakpoint
CREATE INDEX "Upvote_userId_issueId_idx" ON "Upvote" USING btree ("userId","issueId");--> statement-breakpoint
CREATE INDEX "Location_organizationId_idx" ON "Location" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Machine_qrCodeId_idx" ON "Machine" USING btree ("qrCodeId");--> statement-breakpoint
CREATE INDEX "Machine_organizationId_idx" ON "Machine" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Machine_locationId_idx" ON "Machine" USING btree ("locationId");--> statement-breakpoint
CREATE INDEX "Machine_modelId_idx" ON "Machine" USING btree ("modelId");--> statement-breakpoint
CREATE INDEX "Machine_ownerId_idx" ON "Machine" USING btree ("ownerId");--> statement-breakpoint
CREATE INDEX "Membership_userId_organizationId_idx" ON "Membership" USING btree ("userId","organizationId");--> statement-breakpoint
CREATE INDEX "Membership_organizationId_idx" ON "Membership" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "Organization_subdomain_idx" ON "Organization" USING btree ("subdomain");--> statement-breakpoint
CREATE INDEX "_RolePermissions_roleId_idx" ON "_RolePermissions" USING btree ("A");--> statement-breakpoint
CREATE INDEX "_RolePermissions_permissionId_idx" ON "_RolePermissions" USING btree ("B");--> statement-breakpoint
CREATE INDEX "Role_organizationId_idx" ON "Role" USING btree ("organizationId");