name: Node Setup
description: Setup Node and optionally install dependencies

inputs:
  node-version:
    description: Node.js version
    default: '24'
  cache:
    description: Node cache strategy
    default: 'npm'
  install:
    description: Run npm ci (true/false)
    default: 'true'
  working-directory:
    description: Directory in which to run npm ci
    default: '.'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}

    - name: Install dependencies
      if: inputs.install == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci

