coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 1%
        informational: false
      server:
        target: 60%
        threshold: 1%
        paths:
          - "src/server/"
        informational: false
      lib:
        target: 70%
        threshold: 1%
        paths:
          - "src/lib/"
        informational: false
    patch:
      default:
        target: 70%
        threshold: 5%
        informational: true

ignore:
  - "src/test/"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.vitest.test.ts"
  - "**/*.vitest.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "src/_archived_frontend/"
  - "e2e/"
  - "playwright-report/"
  - "test-results/"
  - "*.config.ts"
  - "*.config.js"
  - "scripts/"
  - ".next/"
  - "docs/"

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false

github_checks:
  annotations: true