name: Cleanup Agent Task Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup-task-files:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for AGENT_TASK.md files
        id: check-files
        run: |
          if find . -name "AGENT_TASK.md" -type f | grep -q .; then
            echo "found=true" >> "$GITHUB_OUTPUT"
            echo "Found AGENT_TASK.md files to cleanup:"
            find . -name "AGENT_TASK.md" -type f
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
            echo "No AGENT_TASK.md files found"
          fi

      - name: Remove AGENT_TASK.md files
        if: steps.check-files.outputs.found == 'true'
        run: |
          echo "Removing AGENT_TASK.md files..."
          find . -name "AGENT_TASK.md" -type f -delete
          
      - name: Create cleanup PR
        if: steps.check-files.outputs.found == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: cleanup AGENT_TASK.md files after merge"
          title: "🧹 Auto-cleanup: Remove AGENT_TASK.md files"
          body: |
            ## Automated Cleanup
            
            This PR automatically removes `AGENT_TASK.md` files that were merged into main.
            
            These task files serve their purpose during development but should be cleaned up
            to keep the main branch tidy while preserving the task history in git.
            
            ### Files Removed
            - All `AGENT_TASK.md` files found in the repository
            
            ### Auto-merge
            This PR will be automatically approved and merged.
            
            🤖 *Generated by automated cleanup workflow*
          branch: auto-cleanup/remove-task-files
          delete-branch: true
          
      - name: Auto-approve cleanup PR
        if: steps.check-files.outputs.found == 'true'
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          
      - name: Enable auto-merge
        if: steps.check-files.outputs.found == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash